siteTitle = "wetainment"
siteDescr = "My personal blog/portfolio. ABAP at day, JS at night."
siteAuthor = "Christoph Benjamin Weber"

siteTelegramUrl = ""
siteTwitterUrl = "https://twitter.com/kriswep"
siteGithubUrl = "https://github.com/kriswep"
siteEmailUrl = "mailto:kriswep@wetainment.com"
siteRssUrl = ""
siteVkUrl = ""

googleAnalyticsId = ""

linkPrefix = ""